// Writes the SDK's source into the core as a string.
//
// The bundler has to hand the SDK to esbuild wherever it runs. A Worker has
// no filesystem to read it from, so the source travels inside the code. Run
// this after changing packages/sdk/src/index.ts; a test fails when it is stale.
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const source = fs.readFileSync(path.join(root, "packages/sdk/src/index.ts"), "utf8");
const out = `// Generated by scripts/embed-sdk.mjs from packages/sdk/src/index.ts. Do not edit.
export const SDK_SOURCE = ${JSON.stringify(source)};
`;
fs.writeFileSync(path.join(root, "packages/core/src/sdk-source.generated.ts"), out);
