// Writes the SDK's source into the core as strings.
//
// The bundler has to hand the SDK to esbuild wherever it runs. A browser has
// no filesystem to read it from, so the source travels inside the code. Run
// this after changing a file in packages/sdk/src; a test fails when it is stale.
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const dir = path.join(root, "packages/sdk/src");
const sources = Object.fromEntries(
  fs
    .readdirSync(dir)
    .filter((name) => name.endsWith(".ts"))
    .sort()
    .map((name) => [name, fs.readFileSync(path.join(dir, name), "utf8")]),
);
const out = `// Generated by scripts/embed-sdk.mjs from packages/sdk/src. Do not edit.
export const SDK_SOURCES: Record<string, string> = ${JSON.stringify(sources, null, 2)};
`;
fs.writeFileSync(path.join(root, "packages/core/src/sdk-source.generated.ts"), out);
